apiVersion: v1
kind: Pod
metadata:
  name: pyrun-pod
spec:
  restartPolicy: Never
  containers:
    - name: pyrun
      image: rahulh77/pyrun
      args: ["10"]
      resources:
        requests:
          cpu: 150m
          memory: 200Mi
        limits:
          cpu: 150m
          memory: 200Mi
